-- Data-driven Civilopedia extra pages.
-- CategoryExtras: one row = one custom home page appended after "World Congress" on the home list.
CREATE TABLE CategoryExtras (
	"ID"			integer,
	"Type"			text NOT NULL UNIQUE,
	"Description"	text,		-- home page title (TXT_KEY)
	"Help"			text,		-- home page blurb text (TXT_KEY)
	"IconAtlas"		text,		-- 256x256 portrait atlas name
	"PortraitIndex"	integer,	-- portrait index within the atlas
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("Description") REFERENCES "Language_en_US"("Tag")
);

-- CategoryExtras_Classes: collapsible group under a home page.
CREATE TABLE CategoryExtras_Classes (
	"ID"				integer,
	"CategoryExtraType"	text,	-- parent home page (CategoryExtras.Type)
	"Type"				text NOT NULL UNIQUE,
	"Description"		text,	-- collapsible header title (TXT_KEY)
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("Description") REFERENCES "Language_en_US"("Tag")
);

-- CategoryExtras_Items: individual entry under a collapsible group.
CREATE TABLE CategoryExtras_Items (
	"ID"					integer,
	"CategoryExtraClassType"	text,	-- parent group (CategoryExtras_Classes.Type)
	"Type"					text NOT NULL UNIQUE,
	"Description"			text,	-- entry title (TXT_KEY)
	"Help"					text,	-- entry body text (TXT_KEY)
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("Description") REFERENCES "Language_en_US"("Tag")
);

-- "Super Power Update Log"
INSERT INTO CategoryExtras (Type, Description, Help, IconAtlas, PortraitIndex)
VALUES ('CATEGORY_EXTRA_SP_UPDATE_LOG', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_LOG', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_LOG_HELP', 'TECH_ATLAS_1', 48);

INSERT INTO CategoryExtras_Classes (CategoryExtraType, Type, Description) VALUES
('CATEGORY_EXTRA_SP_UPDATE_LOG', 'CLASS_SP_UPDATE_V7', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V7'),
('CATEGORY_EXTRA_SP_UPDATE_LOG', 'CLASS_SP_UPDATE_V8', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V8'),
('CATEGORY_EXTRA_SP_UPDATE_LOG', 'CLASS_SP_UPDATE_V9', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V9'),
('CATEGORY_EXTRA_SP_UPDATE_LOG', 'CLASS_SP_UPDATE_V10', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10');

INSERT INTO CategoryExtras_Items (CategoryExtraClassType, Type, Description, Help) VALUES
('CLASS_SP_UPDATE_V7', 'ITEM_SP_UPDATE_V7_0', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V7_0', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V7_0_HELP'),
('CLASS_SP_UPDATE_V8', 'ITEM_SP_UPDATE_V8_0', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V8_0', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V8_0_HELP'),
('CLASS_SP_UPDATE_V9', 'ITEM_SP_UPDATE_V9_0', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V9_0', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V9_0_HELP'),
('CLASS_SP_UPDATE_V9', 'ITEM_SP_UPDATE_V9_1', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V9_1', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V9_1_HELP'),
('CLASS_SP_UPDATE_V9', 'ITEM_SP_UPDATE_V9_2', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V9_2', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V9_2_HELP'),
('CLASS_SP_UPDATE_V9', 'ITEM_SP_UPDATE_V9_3', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V9_3', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V9_3_HELP'),
('CLASS_SP_UPDATE_V9', 'ITEM_SP_UPDATE_V9_4', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V9_4', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V9_4_HELP'),
('CLASS_SP_UPDATE_V9', 'ITEM_SP_UPDATE_V9_5', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V9_5', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V9_5_HELP'),
('CLASS_SP_UPDATE_V10', 'ITEM_SP_UPDATE_V10_0', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10_0', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10_0_HELP'),
('CLASS_SP_UPDATE_V10', 'ITEM_SP_UPDATE_V10_5', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10_5', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10_5_HELP'),
('CLASS_SP_UPDATE_V10', 'ITEM_SP_UPDATE_V10_6', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10_6', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10_6_HELP'),
('CLASS_SP_UPDATE_V10', 'ITEM_SP_UPDATE_V10_7', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10_7', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10_7_HELP'),
('CLASS_SP_UPDATE_V10', 'ITEM_SP_UPDATE_V10_8', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10_8', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10_8_HELP'),
('CLASS_SP_UPDATE_V10', 'ITEM_SP_UPDATE_V10_9', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10_9', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10_9_HELP'),
('CLASS_SP_UPDATE_V10', 'ITEM_SP_UPDATE_V10_FINAL', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10_FINAL', 'TXT_KEY_PEDIA_EXTRA_SP_UPDATE_V10_FINAL_HELP');

